version: "3.9"

services:
  app:
    build: ./app
    depends_on:
        - mongo
    networks:
      - app-network

  mongo:
    image: mongo
    networks:
      - app-network

  mongo-express:
    image: mongo-express
    depends_on:
        - mongo
    networks:
      - app-network
    ports:
      - "8888:8081"

networks:
  app-network:
    driver: bridge

